name: GitHub Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:               # allows manual run

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Accra
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_achievements: yes
