name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Replace with your GitHub username
          user: benjamin-nyankson
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Accra
